# Generated by Django 4.0.2 on 2022-05-21 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creted_on',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
