# Generated by Django 4.0.2 on 2022-05-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0002_alter_post_creted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choose_picture',
            field=models.ImageField(default='post', upload_to='post/post_pictures/'),
        ),
    ]
