# Generated by Django 4.0.2 on 2022-05-21 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0003_alter_post_choose_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='choose_picture',
            field=models.ImageField(blank=True, null=True, upload_to='post/post_pictures/'),
        ),
    ]
