# Generated by Django 4.0.2 on 2022-05-23 04:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0005_post_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='creted_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
