# Generated by Django 4.0.2 on 2022-06-19 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_userprofile_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='post/profile_pictures/default.png', upload_to='post/profile_pictures/'),
        ),
    ]
