# Generated by Django 4.0.2 on 2022-08-12 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_image_remove_post_choose_picture_post_choose_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='choose_picture',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='choose_picture',
            new_name='image',
        ),
    ]
