# Generated by Django 4.0.2 on 2022-08-13 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0021_rename_choose_picture_image_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, upload_to='post/post_pictures/'),
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
